---
title: "ST2195 Programming for Data Science"
author: "Lee Hin Sing Raymond"
date: "February 2021"
output: pdf_document
---

# Practice Assignment 6

### Introduction

This is the sixth assignment for the course [**ST2195 Programming for Data Science**](https://www.lse.ac.uk/study-at-lse/uolip/Assets/documents/21-22-CIS-Sheets/ST2195-Programming-for-data-science.pdf). R and Python programming will be the main focus of this introductory course.

This is a compulsory 200-course for students who are going for a **BSc Data Science and Business Analytics** degree in the University of London, the academic direction of the degree program is provided by [London School of Economics and Political Science](https://www.lse.ac.uk/) (LSE). The course convenors are Mr [Ioannis Kosmidis](https://www.ikosmidis.com/) and Dr [Kostas Kalogeropoulos](https://www.lse.ac.uk/Statistics/People/Dr-Kostas-Kalogeropoulos).

Throughout the half-year course, there will be a take-home assignment every two weeks to demonstrate what we have learned before. All final works should be uploaded to a GitHub repository for version control.

### Assignment

Download the [ECB speeches dataset](https://www.ecb.europa.eu/press/key/html/downloads.en.html) and the daily EUR/USD reference exchange rate from the [ECB Statistical Data Warehouse](https://sdw.ecb.europa.eu/). Next, save them as “speeches.csv” and “fx.csv”. For the speeches.csv, please keep only the “date” and “contents” columns.

Create a GitHub repository called “st2195_assignment_6” and include two scripts (one in Python and one in R) to perform the operations described below, and a README.md file:

* Load and merge the datasets keeping all information available for the dates in which there is a measurement in “fx.csv”. [1 point]

* Remove entries with obvious outliers or mistakes, if any. [1.5 points]

* Handle missing observations for the exchange rate, if any. This should be done replacing any missing exchange rate with the latest information available. Whenever this cannot be done, the relevant entry should be removed entirely from the dataset. [1.5 points]

* Calculate the exchange rate return. Extend the original dataset with the following variables: “good_news” (equal to 1 when the exchange rate return is larger than 0.5 percent, 0 otherwise) and “bad_news” (equal to 1 when the exchange rate return is lower than -0.5 percent, 0 otherwise). [1.5 points]

* Remove the entries for which contents column has NA values. Generate and store in csv the following tables [1.5 points each]:
  + “good_indicators” – with the 20 most common words (excluding articles, prepositions and similar connectors) associated with entries wherein “good_news” is equal to 1;
  + “bad_indicators” – with the 20 most common words (excluding articles, prepositions and similar connectors) associated with entries wherein “bad_news” is equal to 1;

  Any observation from the common words found above?

Note that the original data should not be included in the GitHub repository, but only appropriately described and linked in the readme file.